=== prenzelmike/SimpleWebApi/Data/SimpleType.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="mh.dev.st.01" targetNamespace="mh.dev.st.01"
    elementFormDefault="qualified">
    <xs:simpleType name="IntegerNumber">
        <xs:restriction base="xs:int">
            <xs:totalDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="SimpleType">
        <xs:sequence>
            <xs:element name="Id" type="IntegerNumber"></xs:element>
            <xs:element name="Name" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="SimpleTypeDocument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SimpleTypes" type="SimpleType" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== prenzelmike/SimpleWebApi/Data/SimpleTypes.xml
<?xml version="1.0" encoding="utf-8"?>
<SimpleTypeDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xsi:schemaLocation="mh.dev.st.01 SimpleType.xsd" 
  xmlns="mh.dev.st.01">
  <SimpleTypes>
    <Id>1</Id>
    <Name>Erster Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>2</Id>
    <Name>Zweiter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>3</Id>
    <Name>Dritter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>4</Id>
    <Name>Vierter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>5</Id>
    <Name>FÃ¼nfter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>6</Id>
    <Name>Sechster Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>7</Id>
    <Name>Siebter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>8</Id>
    <Name>Achter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>9</Id>
    <Name>Neunter Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>10</Id>
    <Name>Eintrag mit Id 10</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>11</Id>
    <Name>Neuer Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>12</Id>
    <Name>Neuer Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>13</Id>
    <Name>Weiterer Eintrag</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>14</Id>
    <Name>Noch ein weiterer Eintrags</Name>
  </SimpleTypes>
  <SimpleTypes>
    <Id>15</Id>
    <Name>Noch ein weiterer Eintrag hinzu</Name>
  </SimpleTypes>
</SimpleTypeDocument>
